spring:
  application:
    name: lecture-search-system
  profiles:
    active: dev

llm:
  api:
    url: ${llm.api.terms_url}
    key: ${llm.api.key}

langchain4j:
  open-ai:
    streaming-chat-model:
      api-key: ${llm.api.key}
      model-name: ${llm.api.model-name}
      base-url: ${llm.api.chat-url}
    chat-model:
      api-key: ${llm.api.key}
      model-name: ${llm.api.model-name}
      base-url: ${llm.api.chat-url}
